#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &

feh --bg-fill [WALLPAPER] &

compton &
polybar malte &

light-locker &

dunst &

redshift -l 52.267393:8.052631 -t 6500K:3500K &

bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-1 0

bspc config border_width         4
bspc config window_gap          16

bspc config normal_border_color  "#000000"
bspc config focused_border_color "#FFFFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true