dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

amixer sset 'Master' 100%

autorandr-launcher --daemonize

[SCALE_COMMAND]
exec i3
