export ZSH="/home/malte/.oh-my-zsh"

ZSH_THEME="bureau"

plugins=(
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=8'

# The following lines were added by compinstall
zstyle :compinstall filename '/home/malte/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# ROS stuff
ROSVERSION="melodic" 

# check for ros installation
if [ -f "/opt/ros/$ROSVERSION/setup.zsh" ]
then
    source /opt/ros/$ROSVERSION/setup.zsh
fi

# check for local workspace
if [ -f "devel/setup.zsh" ]
then
    source devel/setup.zsh
fi
